<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Jarvis</AssemblyName>
    <RootNamespace>Jarvis.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Jarvis.Codex/Jarvis.Codex.csproj" />
    <ProjectReference Include="../Jarvis.Core/Jarvis.Core.csproj" />
  </ItemGroup>
</Project>
